# Dockerfile.dev
FROM golang:alpine

# ติดตั้ง Air (ตัวช่วย Hot Reload)
# เราใช้ go install เพื่อดึง Air มาติดตั้งใน Container
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy ไฟล์ go.mod และ go.sum ก่อน เพื่อให้ Docker Cache layer นี้ไว้
COPY go.mod go.sum ./
RUN go mod download

# Copy โค้ดทั้งหมด
COPY . .

# สั่งรัน Air แทนการรัน go run main.go
CMD ["air", "-c", ".air.toml"]